apiVersion: operators.sigex.ibm/v1alpha1
kind: ChaosTest
metadata:
  name: example-chaostest
  namespace: kube-system 
spec:
  targetResource: pods
  action: delete
  interval: "10" # in seconds
  ttl: "6" # in interval cycles (TTL + interval = tt time)
