apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chaos-operator
  template:
    metadata:
      labels:
        name: chaos-operator
    spec:
      serviceAccountName: chaos-operator
      containers:
        - name: chaos-operator
          # Replace this with the built image name
          image: jpapejr/chaos-operator:latest
          imagePullPolicy: Always
          command:
          - chaos-operator
          env:
            - name: APISERVER
              value: ""
            - name: TOKEN
              value: ""
            - name: MONKEY_IMAGE
              value: "jpapejr/malevolent-monkey:23e1355a16f463bf8ecf6173db9c61d800a93cb6"
            - name: MONKEY_SERVICE_ACCOUNT
              value: "monkey"
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "chaos-operator"
