apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: chaos-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - jobs
  verbs:
  - '*'
- apiGroups:
  - operators.sigex.ibm
  resources:
  - '*'
  - chaostests
  verbs:
  - '*'
